-- 1. Create Hero Slides Table in Supabase
CREATE TABLE IF NOT EXISTS public.hero_slides (
  id VARCHAR(100) PRIMARY KEY,
  type VARCHAR(50) NOT NULL DEFAULT 'custom',
  is_active BOOLEAN DEFAULT TRUE,
  order_index INT DEFAULT 0,
  eyebrow_en TEXT,
  eyebrow_bn TEXT,
  title_en TEXT NOT NULL,
  title_bn TEXT NOT NULL,
  lead_en TEXT,
  lead_bn TEXT,
  cta_text_en TEXT,
  cta_text_bn TEXT,
  cta_href TEXT,
  cta_type VARCHAR(50) DEFAULT 'whatsapp',
  secondary_cta_text_en TEXT,
  secondary_cta_text_bn TEXT,
  secondary_cta_href TEXT,
  doctor_image TEXT,
  doctor_specialty_en TEXT,
  doctor_specialty_bn TEXT,
  doctor_degrees_en TEXT,
  doctor_degrees_bn TEXT,
  doctor_designation_en TEXT,
  doctor_designation_bn TEXT,
  chamber_hours_highlight_en TEXT,
  chamber_hours_highlight_bn TEXT,
  chamber_address_highlight_en TEXT,
  chamber_address_highlight_bn TEXT,
  chamber_room_en TEXT,
  chamber_room_bn TEXT,
  chamber_room_badge_en TEXT,
  chamber_room_badge_bn TEXT,
  chamber_address_en TEXT,
  chamber_address_bn TEXT,
  chamber_hours_en TEXT,
  chamber_hours_bn TEXT,
  chamber_off_days_en TEXT,
  chamber_off_days_bn TEXT,
  chamber_ticket_phone TEXT,
  chamber_ticket_badge_en TEXT,
  chamber_ticket_badge_bn TEXT,
  chamber_ticket_note_en TEXT,
  chamber_ticket_note_bn TEXT,
  custom_image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;

-- Allow Public Read
CREATE POLICY "Allow public read hero_slides" ON public.hero_slides FOR SELECT USING (true);
CREATE POLICY "Allow auth write hero_slides" ON public.hero_slides FOR ALL TO authenticated USING (true);

-- Seed Default Hero Slides
INSERT INTO public.hero_slides (
  id, type, is_active, order_index,
  eyebrow_en, eyebrow_bn, title_en, title_bn, lead_en, lead_bn,
  cta_text_en, cta_text_bn, cta_href, cta_type,
  secondary_cta_text_en, secondary_cta_text_bn, secondary_cta_href,
  doctor_image, doctor_specialty_en, doctor_specialty_bn,
  doctor_degrees_en, doctor_degrees_bn, doctor_designation_en, doctor_designation_bn,
  chamber_hours_highlight_en, chamber_hours_highlight_bn,
  chamber_address_highlight_en, chamber_address_highlight_bn,
  chamber_room_en, chamber_room_bn, chamber_room_badge_en, chamber_room_badge_bn,
  chamber_address_en, chamber_address_bn, chamber_hours_en, chamber_hours_bn,
  chamber_off_days_en, chamber_off_days_bn, chamber_ticket_phone,
  chamber_ticket_badge_en, chamber_ticket_badge_bn, chamber_ticket_note_en, chamber_ticket_note_bn
) VALUES 
(
  'welcome', 'welcome', true, 0,
  'Medicine Specialist · Sylhet', 'মেডিসিন বিশেষজ্ঞ · সিলেট',
  'Precision Diagnostics & Compassionate Care — Your Health, Our Priority.', 'সঠিক রোগ নির্ণয় ও সুচিকিৎসা — আপনার আস্থায় আমাদের অঙ্গীকার।',
  'Dr. Hanif Ahmed Towhid, Medicine Specialist (Department of Medicine), Sylhet MAG Osmani Medical College Hospital.', 'ডা. হানিফ আহমেদ তৌহিদ, মেডিসিন বিশেষজ্ঞ (মেডিসিন বিভাগ), সিলেট এম.এ.জি. ওসমানী মেডিকেল কলেজ হাসপাতাল।',
  'Call for Serial Booking', 'সিরিয়ালের জন্য কল করুন', 'https://wa.me/8801346132486', 'whatsapp',
  NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
),
(
  'doctor-intro', 'doctor-intro', true, 1,
  NULL, NULL,
  'Dr. Hanif Ahmed Towhid', 'ডা. হানিফ আহমেদ তৌহিদ',
  NULL, NULL,
  'Call for Serial', 'সিরিয়ালের জন্য কল করুন', 'https://wa.me/8801346132486', 'whatsapp',
  'Doctor''s Journey', 'ডাক্তারের জীবন ও ডিগ্রি', '/about',
  '/doctor-hero.png', 'Medicine Specialist', 'মেডিসিন বিশেষজ্ঞ',
  'MBBS, BCS (Health), MCPS (Medicine), FCPS (Medicine)', 'MBBS, BCS (Health), MCPS (Medicine), FCPS (Medicine)',
  'Medicine Specialist (Department of Medicine), Sylhet MAG Osmani Medical College Hospital', 'মেডিসিন বিশেষজ্ঞ (মেডিসিন বিভাগ), সিলেট এম.এ.জি. ওসমানী মেডিকেল কলেজ হাসপাতাল',
  'Patient Viewing: 5:00 PM – 9:00 PM (Friday & Tuesday Closed)', 'রোগী দেখার সময়: প্রতিদিন বিকাল ৫:০০টা – রাত ৯:০০টা (শুক্রবার ও মঙ্গলবার বন্ধ)',
  'Popular Medical Center Ltd. (Room 605), New Medical Road, Kazalshah, Sylhet.', 'পপুলার মেডিকেল সেন্টার লিমিটেড (রুম-৬০৫), নিউ মেডিকেল রোড, কাজলশাহ, সিলেট।',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
),
(
  'conditions', 'conditions', true, 2,
  NULL, NULL,
  'Diseases We Treat', 'যেসব রোগের চিকিৎসা দেওয়া হয়',
  'Tap any condition for instant clinical insights', 'যেকোনো রোগে ক্লিক করে চিকিৎসা পরামর্শ জানুন',
  NULL, NULL, NULL, NULL,
  'View More', 'আরও দেখুন', '/diseases',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
),
(
  'chamber', 'chamber', true, 3,
  'Chamber Location', 'চেম্বারের ঠিকানা ও সময়সূচী',
  'Popular Medical Center Ltd., Sylhet.', 'পপুলার মেডিকেল সেন্টার লিমিটেড, সিলেট।',
  NULL, NULL,
  'Contact Chamber via WhatsApp', 'হোয়াটসঅ্যাপে চেম্বারে যোগাযোগ', 'https://wa.me/8801346132486', 'whatsapp',
  'Direct Call', 'সরাসরি কল করুন', 'tel:01346132486',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  '6th Floor, Room No-605', '৬ষ্ঠ তলা, রুম নং-৬০৫', 'Main Chamber', 'প্রধান চেম্বার',
  'New Medical Road, Kazalshah, Sylhet.', 'নিউ মেডিকেল রোড, কাজলশাহ, সিলেট।',
  '5:00 PM – 9:00 PM (Daily)', 'প্রতিদিন বিকাল ৫:০০টা – রাত ৯:০০টা',
  'Friday & Tuesday Closed', 'শুক্রবার ও মঙ্গলবার চেম্বার বন্ধ থাকে',
  '01346-132486', 'Serial Hotline', 'সিরিয়াল হটলাইন',
  'Call after 9:00 AM to confirm your appointment serial', 'সকাল ৯:০০টার পর কল করে সিরিয়াল বুকিং নিশ্চিত করুন'
)
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  is_active = EXCLUDED.is_active,
  order_index = EXCLUDED.order_index,
  eyebrow_en = EXCLUDED.eyebrow_en,
  eyebrow_bn = EXCLUDED.eyebrow_bn,
  title_en = EXCLUDED.title_en,
  title_bn = EXCLUDED.title_bn,
  lead_en = EXCLUDED.lead_en,
  lead_bn = EXCLUDED.lead_bn,
  cta_text_en = EXCLUDED.cta_text_en,
  cta_text_bn = EXCLUDED.cta_text_bn,
  cta_href = EXCLUDED.cta_href,
  cta_type = EXCLUDED.cta_type,
  secondary_cta_text_en = EXCLUDED.secondary_cta_text_en,
  secondary_cta_text_bn = EXCLUDED.secondary_cta_text_bn,
  secondary_cta_href = EXCLUDED.secondary_cta_href,
  doctor_image = EXCLUDED.doctor_image,
  doctor_specialty_en = EXCLUDED.doctor_specialty_en,
  doctor_specialty_bn = EXCLUDED.doctor_specialty_bn,
  doctor_degrees_en = EXCLUDED.doctor_degrees_en,
  doctor_degrees_bn = EXCLUDED.doctor_degrees_bn,
  doctor_designation_en = EXCLUDED.doctor_designation_en,
  doctor_designation_bn = EXCLUDED.doctor_designation_bn,
  chamber_hours_highlight_en = EXCLUDED.chamber_hours_highlight_en,
  chamber_hours_highlight_bn = EXCLUDED.chamber_hours_highlight_bn,
  chamber_address_highlight_en = EXCLUDED.chamber_address_highlight_en,
  chamber_address_highlight_bn = EXCLUDED.chamber_address_highlight_bn,
  chamber_room_en = EXCLUDED.chamber_room_en,
  chamber_room_bn = EXCLUDED.chamber_room_bn,
  chamber_room_badge_en = EXCLUDED.chamber_room_badge_en,
  chamber_room_badge_bn = EXCLUDED.chamber_room_badge_bn,
  chamber_address_en = EXCLUDED.chamber_address_en,
  chamber_address_bn = EXCLUDED.chamber_address_bn,
  chamber_hours_en = EXCLUDED.chamber_hours_en,
  chamber_hours_bn = EXCLUDED.chamber_hours_bn,
  chamber_off_days_en = EXCLUDED.chamber_off_days_en,
  chamber_off_days_bn = EXCLUDED.chamber_off_days_bn,
  chamber_ticket_phone = EXCLUDED.chamber_ticket_phone,
  chamber_ticket_badge_en = EXCLUDED.chamber_ticket_badge_en,
  chamber_ticket_badge_bn = EXCLUDED.chamber_ticket_badge_bn,
  chamber_ticket_note_en = EXCLUDED.chamber_ticket_note_en,
  chamber_ticket_note_bn = EXCLUDED.chamber_ticket_note_bn,
  updated_at = timezone('utc'::text, now());
